config/routes.rb
Rails.application.routes.draw do
  get 'items/create'

  devise_for :users
  resources :users, only: [:show] do
    resources :items, only: [:create, :update, :destroy]
  end
  get 'welcome/index'
  authenticated :user do
    root to: 'users#show', as: :authenticated_root
  end
  root 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, except: [:create]
  def create
    @item = current_user.items.new(item_params)
    if @item.save
      flash[:notice] = "Item was successfully created"
    else
      flash.now[:alert] = "There was an error in creating your item"
    end
    redirect_to current_user
  end

  def update
    @item.completed = params[:completed]
    if @item.save
      flash[:notice] = "You completed an item. Congrats!"
    else
      flash.now[:alert] = "Something went wrong, try again."
    end
    redirect_to current_user
  end

  def destroy
    if @item.destroy
      flash[:notice] = "Item was successfully destroyed"
    else
      flash.now[:alert] = "There was an error in deleting your item"
    end
    redirect_to current_user
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = params[:id].present? ? User.find(params[:id]) : current_user
    @pending_items = @user.items.where(completed: false)
    @completed_items = @user.items.where(completed: true)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [user, item] do |f| %>
  <div class="form-group">
    <div class="col-md-8">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter to-do item' %>
    </div>
    <div class="col-md-4">
      <%= f.submit "Add", class: 'btn btn-success'%>
    </div>
  </div>
<% end %>

app/views/items/_item.html.erb
<div class="media">
  <div class="media-body col-md-8">
    <p><%= item.name %></p>
    <i><%= distance_of_time_in_words(item.created_at + 7.days, Time.now) %> left</i>
  </div>
  <div class="media-body col-md-4">
    <% if current_user == @user %>
      <% if item.completed == false %>
        <%= link_to '', user_item_path(current_user, item, completed: true), method: :patch, class: 'glyphicon glyphicon-ok' %>
      <% else %>
        <%= link_to '', user_item_path(current_user, item, completed: false), method: :patch, class: 'glyphicon glyphicon-repeat' %>
      <% end %>
      <%= link_to '', user_item_path(current_user, item), method: :delete, class: 'glyphicon glyphicon-remove' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1"  />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <div class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <div class="pull-right user-info">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> -
          <%= link_to 'Show Profile', user_path(current_user), :class => 'navbar-link' %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </div>

  <%= yield %>

  </div>

</body>
</html>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h3>To Do List</h3>
    <div>
      <%= render @pending_items %>
      <% if current_user == @user %>
        <%= render 'items/form', user: @user, item: Item.new %>
      <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <h3>Completed Items</h3>
    <div>
      <%= render @completed_items %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>